package com.jayqqaa12.auto.base.system;

import com.jayqqaa12.jbase.jfinal.ext.model.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBug<M extends BaseBug<M>> extends Model<M> implements IBean {

	public static final String ID = "id"; 
	public static final String NAME = "name"; 
	public static final String DES = "des"; 
	public static final String TYPE = "type"; 
	public static final String CREATEDATE = "createdate"; 
	public static final String MODIFYDATE = "modifydate"; 
	public static final String STATUS = "status"; 
	public M setId(Object id) {
		 return set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setName(Object name) {
		 return set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setDes(Object des) {
		 return set("des", des);
	}

	public java.lang.String getDes() {
		return get("des");
	}

	public M setType(Object type) {
		 return set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setCreatedate(Object createdate) {
		 return set("createdate", createdate);
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public M setModifydate(Object modifydate) {
		 return set("modifydate", modifydate);
	}

	public java.util.Date getModifydate() {
		return get("modifydate");
	}

	public M setStatus(Object status) {
		 return set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
