package com.jayqqaa12.auto.base.system;

import com.jayqqaa12.jbase.jfinal.ext.model.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRes<M extends BaseRes<M>> extends Model<M> implements IBean {

	public static final String ID = "id"; 
	public static final String PID = "pid"; 
	public static final String NAME = "name"; 
	public static final String DES = "des"; 
	public static final String URL = "url"; 
	public static final String ICONCLS = "iconCls"; 
	public static final String SEQ = "seq"; 
	public static final String TYPE = "type"; 
	public static final String MODIFYDATE = "modifydate"; 
	public M setId(Object id) {
		 return set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setPid(Object pid) {
		 return set("pid", pid);
	}

	public java.lang.Integer getPid() {
		return get("pid");
	}

	public M setName(Object name) {
		 return set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setDes(Object des) {
		 return set("des", des);
	}

	public java.lang.String getDes() {
		return get("des");
	}

	public M setUrl(Object url) {
		 return set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setIconCls(Object iconCls) {
		 return set("iconCls", iconCls);
	}

	public java.lang.String getIconCls() {
		return get("iconCls");
	}

	public M setSeq(Object seq) {
		 return set("seq", seq);
	}

	public java.lang.Integer getSeq() {
		return get("seq");
	}

	public M setType(Object type) {
		 return set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public M setModifydate(Object modifydate) {
		 return set("modifydate", modifydate);
	}

	public java.util.Date getModifydate() {
		return get("modifydate");
	}

}
