package com.jayqqaa12.auto.base.system;

import com.jayqqaa12.jbase.jfinal.ext.model.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public static final String ID = "id"; 
	public static final String NAME = "name"; 
	public static final String PWD = "pwd"; 
	public static final String DES = "des"; 
	public static final String STATUS = "status"; 
	public static final String ICON = "icon"; 
	public static final String EMAIL = "email"; 
	public static final String CREATEDATE = "createdate"; 
	public static final String PHONE = "phone"; 
	public static final String SALT2 = "salt2"; 
	public M setId(Object id) {
		 return set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setName(Object name) {
		 return set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setPwd(Object pwd) {
		 return set("pwd", pwd);
	}

	public java.lang.String getPwd() {
		return get("pwd");
	}

	public M setDes(Object des) {
		 return set("des", des);
	}

	public java.lang.String getDes() {
		return get("des");
	}

	public M setStatus(Object status) {
		 return set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setIcon(Object icon) {
		 return set("icon", icon);
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

	public M setEmail(Object email) {
		 return set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setCreatedate(Object createdate) {
		 return set("createdate", createdate);
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public M setPhone(Object phone) {
		 return set("phone", phone);
	}

	public java.lang.Integer getPhone() {
		return get("phone");
	}

	public M setSalt2(Object salt2) {
		 return set("salt2", salt2);
	}

	public java.lang.String getSalt2() {
		return get("salt2");
	}

}
