package com.jayqqaa12.auto.base.system;

import com.jayqqaa12.jbase.jfinal.ext.model.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public static final String ID = "id"; 
	public static final String UID = "uid"; 
	public static final String BROWSER = "browser"; 
	public static final String OPERATION = "operation"; 
	public static final String FROM = "from"; 
	public static final String IP = "ip"; 
	public static final String URL = "url"; 
	public static final String DATE = "date"; 
	public M setId(Object id) {
		 return set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUid(Object uid) {
		 return set("uid", uid);
	}

	public java.lang.Integer getUid() {
		return get("uid");
	}

	public M setBrowser(Object browser) {
		 return set("browser", browser);
	}

	public java.lang.String getBrowser() {
		return get("browser");
	}

	public M setOperation(Object operation) {
		 return set("operation", operation);
	}

	public java.lang.Integer getOperation() {
		return get("operation");
	}

	public M setFrom(Object from) {
		 return set("from", from);
	}

	public java.lang.String getFrom() {
		return get("from");
	}

	public M setIp(Object ip) {
		 return set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public M setUrl(Object url) {
		 return set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setDate(Object date) {
		 return set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

}
