package com.jayqqaa12.auto.base.system;

import com.jayqqaa12.jbase.jfinal.ext.model.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRole<M extends BaseUserRole<M>> extends Model<M> implements IBean {

	public static final String ID = "id"; 
	public static final String USER_ID = "user_id"; 
	public static final String ROLE_ID = "role_id"; 
	public M setId(Object id) {
		 return set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUserId(Object userId) {
		 return set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public M setRoleId(Object roleId) {
		 return set("role_id", roleId);
	}

	public java.lang.Integer getRoleId() {
		return get("role_id");
	}

}
