package com.jayqqaa12.model.system;

import com.jayqqaa12.auto.base.system.BaseRoleRes;

/**
 * Generated by Jbase .
 */
@SuppressWarnings("serial")
public class RoleRes extends BaseRoleRes<RoleRes> {
	public static final RoleRes dao = new RoleRes();
}
