package com.jayqqaa12.model.system;

import com.jayqqaa12.auto.base.system.BaseUserRole;

/**
 * Generated by Jbase .
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	public static final UserRole dao = new UserRole();
}
