package com.jayqqaa12.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("system_bug", "id", com.jayqqaa12.model.system.Bug.class);
		arp.addMapping("system_log", "id", com.jayqqaa12.model.system.Log.class);
		arp.addMapping("system_res", "id", com.jayqqaa12.model.system.Res.class);
		arp.addMapping("system_role", "id", com.jayqqaa12.model.system.Role.class);
		arp.addMapping("system_role_res", "id", com.jayqqaa12.model.system.RoleRes.class);
		arp.addMapping("system_user", "id", com.jayqqaa12.model.system.User.class);
		arp.addMapping("system_user_role", "id", com.jayqqaa12.model.system.UserRole.class);
		
		System.out.println("loading mapping ok");
	}
}

